import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} container p-2 mx-auto`}>
        <nav>
          <ul>
            <li>
              <Link href="/">All</Link>
            </li>
            <li>
              <Link href="/mythic">Mythic+</Link>
            </li>
            <li>
              <Link href="mythic-glory">Mythic Glory</Link>
            </li>
          </ul>
        </nav>
        <>{children}</>
      </body>
    </html>
  );
}
